# Generated by Django 5.1.6 on 2025-07-18 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 20, 22, 52, 629373, tzinfo=datetime.timezone.utc)),
        ),
    ]
