# Generated by Django 5.1.6 on 2025-07-18 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 17, 20, 29, 55, 825004, tzinfo=datetime.timezone.utc)),
        ),
    ]
