# Generated by Django 5.1.6 on 2025-07-21 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 13, 7, 51, 46511, tzinfo=datetime.timezone.utc)),
        ),
    ]
