# Generated by Django 5.1.6 on 2025-07-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for applications', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_type',
            field=models.CharField(choices=[('DIGITAL', 'Digital'), ('FACE_TO_FACE', 'Face-to-Face')], default='DIGITAL', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='location_address',
            field=models.CharField(blank=True, help_text='Physical address for Face-to-Face interviews', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='max_applications',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of applications allowed', null=True),
        ),
    ]
