# Generated by Django 5.1.6 on 2025-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_job_expires_at_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=20),
        ),
    ]
