# Generated by Django 5.1.6 on 2025-08-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_communityquestion_communityanswer_savedjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='auto_attach_resume_on_apply',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='calendar_token',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='min_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='portfolio_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='preferred_job_types_csv',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='preferred_locations_csv',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='resume_include_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='resume_template',
            field=models.CharField(choices=[('ats', 'ATS'), ('modern', 'Modern'), ('classic', 'Classic')], default='ats', max_length=16),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
