# Generated by Django 5.1.6 on 2025-08-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_usersettings_auto_attach_resume_on_apply_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_attach_resume_on_apply',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='calendar_token',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='min_salary',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='portfolio_public',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='preferred_job_types_csv',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='preferred_locations_csv',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='resume_include_photo',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='resume_template',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='timezone',
        ),
    ]
