# Generated by Django 5.1.6 on 2025-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_usersettings_auto_attach_resume_on_apply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(blank=True, choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=2),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(blank=True, choices=[('auto', 'Auto'), ('light', 'Light'), ('dark', 'Dark')], default='auto', max_length=10),
        ),
    ]
