# Generated by Django 5.1.6 on 2025-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_is_active'),
        ('jobs', '0011_usersettings_compact_mode_usersettings_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='declared_skills',
            field=models.ManyToManyField(blank=True, related_name='applications_declared', to='accounts.skill'),
        ),
    ]
