# Generated by Django 5.1.6 on 2025-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_physical',
            field=models.BooleanField(default=False, help_text='For internships: Check if physical presence required'),
        ),
        migrations.AddField(
            model_name='job',
            name='paid_type',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=6),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_type',
            field=models.CharField(blank=True, choices=[('HOURLY', 'Per Hour'), ('DAILY', 'Per Day')], max_length=6, null=True),
        ),
    ]
