# Generated by Django 5.1.6 on 2025-08-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_employerprofile_phone_number_and_more'),
        ('jobs', '0014_job_is_physical_job_paid_type_job_salary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notifications', to='accounts.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_read', '-created_at'], name='jobs_studen_student_690c43_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'job'), name='uniq_student_job_newjob_notif')],
            },
        ),
    ]
