# Generated by Django 5.1.6 on 2025-08-14 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_alter_user_is_active'),
        ('jobs', '0011_usersettings_compact_mode_usersettings_font_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentBlueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('internship', 'Internship'), ('gig', 'Gig')], max_length=16)),
                ('rules', models.JSONField()),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(240)])),
            ],
        ),
        migrations.CreateModel(
            name='RoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField()),
                ('tasks', models.JSONField(blank=True, null=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(default='invited', max_length=24)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='jobs.application')),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentblueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('qtype', models.CharField(choices=[('mcq', 'MCQ'), ('short', 'Short'), ('code', 'Code')], max_length=8)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('choices', models.JSONField(blank=True, null=True)),
                ('answer_key', models.CharField(blank=True, max_length=8)),
                ('language', models.CharField(blank=True, max_length=32)),
                ('starter_code', models.TextField(blank=True)),
                ('tests', models.JSONField(blank=True, null=True)),
                ('section', models.CharField(default='technical', max_length=24)),
                ('active', models.BooleanField(default=True)),
                ('skills', models.ManyToManyField(blank=True, to='accounts.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField()),
                ('per_skill', models.JSONField()),
                ('per_section', models.JSONField(default=dict)),
                ('summary', models.TextField()),
                ('pdf_path', models.CharField(blank=True, max_length=256)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_type', models.CharField(default='q', max_length=8)),
                ('ref_id', models.IntegerField()),
                ('answer', models.JSONField()),
                ('is_correct', models.BooleanField(null=True)),
                ('score', models.FloatField(default=0.0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentblueprint',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.roleprofile'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField()),
                ('ttype', models.CharField(choices=[('upload', 'Upload'), ('critique', 'Critique')], max_length=16)),
                ('artifact_type', models.CharField(blank=True, max_length=24)),
                ('rubric', models.JSONField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=10)),
                ('active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.roleprofile')),
                ('skills', models.ManyToManyField(blank=True, to='accounts.skill')),
            ],
        ),
    ]
