# Generated by Django 5.1.6 on 2025-08-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('jobs', '0012_application_declared_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantChosenSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_skills', to='jobs.application')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessmentskill')),
            ],
            options={
                'unique_together': {('application', 'skill')},
            },
        ),
    ]
