# Generated by Django 5.1.6 on 2025-08-15 16:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0014_job_is_physical_job_paid_type_job_salary_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('released', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('stripe_payment_id', models.CharField(blank=True, max_length=255)),
                ('withdrawn', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField(help_text='Describe the task or internship duties')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignment', to='jobs.application')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_given', models.TextField(help_text='What was the task given?')),
                ('performance', models.TextField(help_text='How did the student perform?')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating out of 5')),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='payment.taskassignment')),
            ],
        ),
    ]
