# Generated by Django 5.1.6 on 2025-08-15 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_file', models.FileField(blank=True, help_text='Upload your work file', null=True, upload_to='task_submissions/')),
                ('description', models.TextField(help_text='Describe tools, technologies, or details of your work')),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='payment.taskassignment')),
            ],
        ),
    ]
