# Generated by Django 5.1.6 on 2025-07-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employerprofile_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id_document',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id_verified',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='university',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='university_email',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('FT', 'Full-time (40+ hrs/week)'), ('PT', 'Part-time (<30 hrs/week)'), ('WE', 'Weekends only'), ('FL', 'Freelance (Flexible hours)')], help_text='Your weekly availability for work', max_length=2),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='work_preference',
            field=models.CharField(blank=True, choices=[('INT', 'Internship'), ('GIG', 'Gigs'), ('BOTH', 'Both Internship & Gigs')], help_text="Type of work you're looking for", max_length=4),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Doctorate')], max_length=50)),
                ('institution', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('currently_studying', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio_images/')),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.portfolioitem')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.portfolioitem')),
            ],
        ),
    ]
