# Generated by Django 5.1.6 on 2025-07-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill_remove_studentprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
