# Generated by Django 5.1.6 on 2025-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_skill_options_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
