# Generated by Django 5.1.6 on 2025-07-16 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_employerprofile_approved_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='verification_date',
        ),
    ]
