# Generated by Django 5.1.6 on 2025-07-17 14:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_studentprofile_verification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='url',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='university_email',
        ),
        migrations.AddField(
            model_name='experience',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='experience_docs/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='is_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_media/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('HS', 'High School'), ('BA', 'Bachelor'), ('MA', 'Master'), ('PHD', 'PhD'), ('OTHER', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.studentprofile'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('FULL', 'Full-time'), ('PART', 'Part-time'), ('FLEX', 'Flexible')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='work_preference',
            field=models.CharField(blank=True, choices=[('INT', 'Internship'), ('GIG', 'Gigs'), ('BOTH', 'Both')], max_length=4, null=True),
        ),
    ]
