# Generated by Django 5.1.6 on 2025-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID for payments', max_length=255),
        ),
    ]
