# Generated by Django 5.1.6 on 2025-08-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_studentprofile_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
