# Generated by Django 5.1.6 on 2025-08-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_studentprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_email_verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
