# Generated by Django 5.1.6 on 2025-08-22 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_personal_email_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+CCXXXXXXXXXX' (2-digit country code + 10-digit number).", regex='^\\+\\d{12}$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+CCXXXXXXXXXX' (2-digit country code + 10-digit number).", regex='^\\+\\d{12}$')]),
        ),
    ]
